//
// Created by matt on 11/20/2024.
//

#ifndef QMK_USERSPACE_USER_SONG_LIST_H
#define QMK_USERSPACE_USER_SONG_LIST_H
#endif // QMK_USERSPACE_USER_SONG_LIST_H


#define STARTUP_SOUND_CUSTOM E__NOTE(_E3), E__NOTE(_A3), ED_NOTE(_E4),

#define GOODBYE_SOUND_CUSTOM E__NOTE(_E4), E__NOTE(_A3), ED_NOTE(_E3),
