#pragma once

enum {
    OS_WIN_LAYOUT,
    OS_MAC_LAYOUT,
    FKEYS_LAYOUT,
    NAV_LAYOUT,
    NUMKEYS_LAYOUT,
    GAMING_LAYOUT,
    GAMINGFAST_LAYOUT,
    NUMKEYS_GAMING,
    FKEYS_GAMING,
    UTIL_LAYOUT
};
